version: '3.3'

services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

  db_application_system:
    image: postgres:11.6
    container_name: db_application_system
    networks:
      - local
    environment:
      - POSTGRES_PASSWORD=XjFsvIrGyCCrdE
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DEV_DB_USER=dev_db
      - DEV_DB_PASS=dev_db
      - DEV_DB_NAME=dev_db
    volumes:
      - ./bin/startup.sql:/docker-entrypoint-initdb.d/startup.sql

networks:
  local:
